### ISSUE TITLE
add language tag in pop up html

### ISSUE THREAD

**Issue by Kilerd** [Kilerd/StarManager#1]
in Github API, every repository has a field representing its language.
maybe i can add it to pop up HTML showing the language

**Comment by stevinus73** [comment]
what

**Comment by stevinus73** [comment]
Pardon?

**Comment by stevinus73** [comment]
you should github here
i don't have the popup but it is working for other users

**Comment by stevinus73** [comment]
at my java_project

**Comment by Kilerd** [comment]
I can't understand what you are talking about. 
For each repository, github analyzes which language the file uses and counts them. The main program language is the one used  most in the repository.
This issue is discussing whether the main language should be shown in pop up page of the extension and other informations such as repository license, star number and fork number etc.

**Comment by stevinus73** [comment]
oh, you should add them as a pull request

**Comment by stevinus73** [comment]
so where is the popup file?
